[package]
name = "link-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["blocking", "rustls-tls"] }
scraper = "0.23.1"
thiserror = "2.0.12"
